name: Tweetizer
on: [push]

jobs:
  build:
    name: Tweetizer Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 14
        id: java
      - name: Echo
        run: echo 'The time was ${{ steps.java.outputs.time }}'